require('settings')
require('keybindings')
require('autocmds')
require('plugins')
require('plugins.cmp')
require('plugins.lualine')
require('plugins.treesitter')
require('plugins.dap')
require('plugins.autopairs')
require('lsp')

